-- Supabase setup for Huawei Cloud Match
-- Run once in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.
-- Then fill the table with:  python seed_partners.py  and  python add_partners.py

-- 1. Vector extension (pgvector)
create extension if not exists vector;

-- 2. Partner table: business data + 768-dim embedding from Ollama (nomic-embed-text)
create table if not exists public.partner_profiles (
    id           bigint generated by default as identity primary key,
    company_name text not null unique,
    industry     text,
    objectives   text,
    embedding    vector(768)
);

-- 3. Semantic search: cosine similarity between the query and each partner
create or replace function public.match_partners(
    query_embedding vector(768),
    match_threshold float,
    match_count     int
)
returns table (
    id           bigint,
    company_name text,
    industry     text,
    objectives   text,
    similarity   float
)
language sql stable
as $$
    select
        p.id,
        p.company_name,
        p.industry,
        p.objectives,
        1 - (p.embedding <=> query_embedding) as similarity
    from public.partner_profiles p
    where p.embedding is not null
      and 1 - (p.embedding <=> query_embedding) > match_threshold
    order by p.embedding <=> query_embedding
    limit match_count;
$$;
